export default {
    player: { x: 1, y: 5, visible: true },
    // player: { x: 8, y: 3 },
    blocks: [
        { x: 0, y: 8, visible: true },
        { x: 0, y: 7, visible: true },
        { x: 0, y: 6, visible: true },
        { x: 0, y: 5, visible: true },
        { x: 1, y: 1, visible: true },
        { x: 1, y: 2, visible: true },
        { x: 1, y: 3, visible: true },
        { x: 2, y: 3, visible: true },
        { x: 2, y: 4, visible: true },
        { x: 2, y: 5, visible: true },
        { x: 2, y: 6, visible: true },
        { x: 2, y: 8, visible: true },
        { x: 3, y: 1, visible: true },
        { x: 3, y: 4, visible: true },
        { x: 4, y: 1, visible: true },
        { x: 4, y: 2, visible: true },
        { x: 4, y: 4, visible: true },
        { x: 4, y: 6, visible: true },
        { x: 4, y: 7, visible: true },
        { x: 4, y: 8, visible: true },
        { x: 5, y: 0, visible: true },
        { x: 5, y: 1, visible: true },
        { x: 5, y: 4, visible: true },
        { x: 5, y: 8, visible: true },
        { x: 6, y: 3, visible: true },
        { x: 6, y: 4, visible: true },
        { x: 6, y: 6, visible: true },
        { x: 7, y: 1, visible: true },
        { x: 7, y: 2, visible: true },
        { x: 7, y: 3, visible: true },
        { x: 7, y: 6, visible: true },
        { x: 7, y: 7, visible: true },
        { x: 7, y: 8, visible: true },
        { x: 8, y: 5, visible: true },
        { x: 8, y: 6, visible: true },
        { x: 8, y: 8, visible: true },
        { x: 9, y: 0, visible: true },
        { x: 9, y: 1, visible: true },
        { x: 9, y: 3, visible: true },
        { x: 10, y: 0, visible: true },
        { x: 10, y: 3, visible: true },
        { x: 10, y: 4, visible: true },
        { x: 10, y: 6, visible: true },
        { x: 10, y: 7, visible: true },
        { x: 10, y: 8, visible: true },
        { x: 11, y: 0, visible: true },
        { x: 11, y: 4, visible: true },
        { x: 11, y: 7, visible: true },
        { x: 12, y: 0, visible: true },
        { x: 12, y: 4, visible: true },
        { x: 12, y: 5, visible: true },
        { x: 12, y: 7, visible: true },
        { x: 13, y: 0, visible: true },
        { x: 13, y: 7, visible: true },
        { x: 14, y: 0, visible: true },
        { x: 14, y: 4, visible: true },
        { x: 14, y: 5, visible: true },
        { x: 15, y: 5, visible: true },
        { x: 15, y: 7, visible: true },
        { id: "wall1", x: 9, y: 2, visible: false },
        { id: "wall2", x: 13, y: 4, visible: false },
    ],
    coins: [
        { id: "coin1", x: 0, y: 1, visible: true },
        { id: "coin2", x: 3, y: 7, visible: true },
        { id: "coin3", x: 14, y: 2, visible: true },
        { id: "coin4", x: 8, y: 2, visible: true },
        { id: "coin5", x: 13, y: 6, visible: true }
    ],
    goals: [
        { id: "goal1", x: 12, y: 2, visible: true }
    ],
    triggers: [
        { id:"appearwall1", target: "wall1", set: { visible: true }, conditions: { from: "coin4" } },
        { id:"appearwall2", target: "wall2", set: { visible: true }, conditions: { from: "coin5" } },
    ],
    texts: [
        { x: 0.1, y: 0.98, value: "Level 2: aMazing !", size: 12, animStrength: 0.0001 }
    ]
}